Add automatic version updates for github actions with dependabot
skills/template-template pull request #18
Opened 2022-08-22 12:44 UTC by iemejia

### Why:

We can include the dependabot configuration for github actions version updates as part of the templates so downstream keep their projects CI updated.

### What's being changed:

Add a dependabot file (we require still to manually activate dependabot on the template repo settings).

### Check off the following:

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [ ] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2022-08-22 12:44 UTC, iemejia commented
This is a follow up of https://github.com/skills/continuous-delivery-azure/pull/10

2022-10-19 21:42 UTC, heiskr requested changes

2022-10-19 21:42 UTC, heiskr commented on .github/dependabot.yml
> +      interval: "daily"
```suggestion
      interval: "monthly"
```

2022-10-21 18:02 UTC, iemejia commented
PTAL again @heiskr

2022-10-21 19:36 UTC, heiskr approved these changes

2022-10-21 19:36 UTC, merged